/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Distimer Swagger API
 * OpenAPI spec version: 1.0
 */
import type { SubjectctrlSubjectDTO } from './subjectctrlSubjectDTO';

export interface CategoryctrlCategoryDTO {
  id: string;
  name: string;
  /** @minimum 0 */
  order: number;
  subjects: SubjectctrlSubjectDTO[];
}
