/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Distimer Swagger API
 * OpenAPI spec version: 1.0
 */

export interface CategoryctrlModifyCategoryRes {
  id?: string;
  name?: string;
}
