/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Distimer Swagger API
 * OpenAPI spec version: 1.0
 */

export type GetStudylogParams = {
/**
 * count
 */
count: number;
/**
 * offset
 */
offset: number;
};
