/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Distimer Swagger API
 * OpenAPI spec version: 1.0
 */

export type GetStudylogTermParams = {
/**
 * 2006-01-02
 */
start_date: string;
/**
 * 2006-01-03
 */
end_date: string;
};
