/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Distimer Swagger API
 * OpenAPI spec version: 1.0
 */

export interface GroupctrlGroupDTO {
  create_at: string;
  description: string;
  id: string;
  invite_policy: number;
  name: string;
  nickname_policy: string;
  owner_nickname: string;
  reveal_policy: number;
}
