/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Distimer Swagger API
 * OpenAPI spec version: 1.0
 */

export interface GroupctrlModifyMemberReq {
  nickname: string;
  /**
   * @minimum 0
   * @maximum 1
   */
  role: number;
}
