/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Distimer Swagger API
 * OpenAPI spec version: 1.0
 */
import type { SubjectctrlSubjectDTO } from './subjectctrlSubjectDTO';

export interface StudylogctrlGroupStudyLogDTO {
  category_id: string;
  category_name: string;
  content: string;
  end_at: string;
  id: string;
  start_at: string;
  subject: SubjectctrlSubjectDTO;
}
