/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Distimer Swagger API
 * OpenAPI spec version: 1.0
 */

export interface StudylogctrlMyStudyLogDTO {
  content: string;
  end_at: string;
  groups_to_share: string[];
  id: string;
  start_at: string;
  subject_id: string;
}
