/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Distimer Swagger API
 * OpenAPI spec version: 1.0
 */
import type { StudylogctrlGroupMemberdailySubjectLog } from './studylogctrlGroupMemberdailySubjectLog';

export interface StudylogctrlGroupMemberdailyStudyLog {
  date: string;
  log: StudylogctrlGroupMemberdailySubjectLog[];
}
