/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Distimer Swagger API
 * OpenAPI spec version: 1.0
 */
import type { SubjectctrlCreateSubjectBatchElemReq } from './subjectctrlCreateSubjectBatchElemReq';

export interface SubjectctrlCreateSubjectBatchReq {
  subject_list: SubjectctrlCreateSubjectBatchElemReq[];
}
