/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Distimer Swagger API
 * OpenAPI spec version: 1.0
 */

export interface TimerctrlModifyTimerDTO {
  content: string;
  shared_group_ids: string[];
  subject_id: string;
}
