/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Distimer Swagger API
 * OpenAPI spec version: 1.0
 */
import type { GroupctrlAffiliationDTO } from './groupctrlAffiliationDTO';
import type { SubjectctrlSubjectDTO } from './subjectctrlSubjectDTO';

export interface TimerctrlTimerWithEdgeInfoDTO {
  affiliation: GroupctrlAffiliationDTO;
  content: string;
  id: string;
  start_at: string;
  subject: SubjectctrlSubjectDTO;
}
