/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Distimer Swagger API
 * OpenAPI spec version: 1.0
 */

export interface UserctrlMyUserInfoRes {
  created_at: string;
  name: string;
  oauth_provider: number;
  terms_agreed: boolean;
  user_id: string;
}
