/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Distimer Swagger API
 * OpenAPI spec version: 1.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery
} from '@tanstack/react-query'
import type {
  DefinedInitialDataOptions,
  DefinedUseInfiniteQueryResult,
  DefinedUseQueryResult,
  InfiniteData,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query'
import type {
  GetStudylogDateParams,
  GetStudylogGroupStatisticsTermGroupIdMemberIdParams,
  GetStudylogGroupTermGroupIdMemberIdParams,
  GetStudylogParams,
  GetStudylogStatisticsDateParams,
  GetStudylogStatisticsTermParams,
  GetStudylogSubjectIdParams,
  GetStudylogTermParams,
  StudylogctrlCreateStudyLogReq,
  StudylogctrlCreateStudyLogReqBody,
  StudylogctrlDailyStudyLog,
  StudylogctrlDailySubjectLog,
  StudylogctrlGroupMemberdailyStudyLog,
  StudylogctrlGroupStudyLogDTO,
  StudylogctrlMyStudyLogDTO
} from '../../schemas'
import { customInstance } from '../../mutator/axios';
import type { ErrorType, BodyType } from '../../mutator/axios';


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


/**
 * @summary Get All My Study Logs
 */
export const getStudylog = (
    params: GetStudylogParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<StudylogctrlMyStudyLogDTO[]>(
      {url: `/studylog`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getGetStudylogQueryKey = (params: GetStudylogParams,) => {
    return [`/studylog`, ...(params ? [params]: [])] as const;
    }

    
export const getGetStudylogInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getStudylog>>>, TError = ErrorType<unknown>>(params: GetStudylogParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylog>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStudylogQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStudylog>>> = ({ signal }) => getStudylog(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylog>>, TError, TData> & { queryKey: QueryKey }
}

export type GetStudylogInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getStudylog>>>
export type GetStudylogInfiniteQueryError = ErrorType<unknown>


export function useGetStudylogInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylog>>>, TError = ErrorType<unknown>>(
 params: GetStudylogParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylog>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylog>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylogInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylog>>>, TError = ErrorType<unknown>>(
 params: GetStudylogParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylog>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylog>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylogInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylog>>>, TError = ErrorType<unknown>>(
 params: GetStudylogParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylog>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary Get All My Study Logs
 */

export function useGetStudylogInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylog>>>, TError = ErrorType<unknown>>(
 params: GetStudylogParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylog>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetStudylogInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions) as  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getGetStudylogQueryOptions = <TData = Awaited<ReturnType<typeof getStudylog>>, TError = ErrorType<unknown>>(params: GetStudylogParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylog>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStudylogQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStudylog>>> = ({ signal }) => getStudylog(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStudylog>>, TError, TData> & { queryKey: QueryKey }
}

export type GetStudylogQueryResult = NonNullable<Awaited<ReturnType<typeof getStudylog>>>
export type GetStudylogQueryError = ErrorType<unknown>


export function useGetStudylog<TData = Awaited<ReturnType<typeof getStudylog>>, TError = ErrorType<unknown>>(
 params: GetStudylogParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylog>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylog>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylog<TData = Awaited<ReturnType<typeof getStudylog>>, TError = ErrorType<unknown>>(
 params: GetStudylogParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylog>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylog>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylog<TData = Awaited<ReturnType<typeof getStudylog>>, TError = ErrorType<unknown>>(
 params: GetStudylogParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylog>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary Get All My Study Logs
 */

export function useGetStudylog<TData = Awaited<ReturnType<typeof getStudylog>>, TError = ErrorType<unknown>>(
 params: GetStudylogParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylog>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetStudylogQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Create Study Log
 */
export const postStudylog = (
    studylogctrlCreateStudyLogReqBody: BodyType<StudylogctrlCreateStudyLogReqBody>,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<StudylogctrlMyStudyLogDTO>(
      {url: `/studylog`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: studylogctrlCreateStudyLogReqBody
    },
      options);
    }
  


export const getPostStudylogMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postStudylog>>, TError,{data: BodyType<StudylogctrlCreateStudyLogReqBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof postStudylog>>, TError,{data: BodyType<StudylogctrlCreateStudyLogReqBody>}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postStudylog>>, {data: BodyType<StudylogctrlCreateStudyLogReqBody>}> = (props) => {
          const {data} = props ?? {};

          return  postStudylog(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostStudylogMutationResult = NonNullable<Awaited<ReturnType<typeof postStudylog>>>
    export type PostStudylogMutationBody = BodyType<StudylogctrlCreateStudyLogReqBody>
    export type PostStudylogMutationError = ErrorType<void>

    /**
 * @summary Create Study Log
 */
export const usePostStudylog = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postStudylog>>, TError,{data: BodyType<StudylogctrlCreateStudyLogReqBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof postStudylog>>,
        TError,
        {data: BodyType<StudylogctrlCreateStudyLogReqBody>},
        TContext
      > => {

      const mutationOptions = getPostStudylogMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Get StudyLog by Date
 */
export const getStudylogDate = (
    params?: GetStudylogDateParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<StudylogctrlMyStudyLogDTO[]>(
      {url: `/studylog/date`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getGetStudylogDateQueryKey = (params?: GetStudylogDateParams,) => {
    return [`/studylog/date`, ...(params ? [params]: [])] as const;
    }

    
export const getGetStudylogDateInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getStudylogDate>>>, TError = ErrorType<void>>(params?: GetStudylogDateParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogDate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStudylogDateQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStudylogDate>>> = ({ signal }) => getStudylogDate(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogDate>>, TError, TData> & { queryKey: QueryKey }
}

export type GetStudylogDateInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getStudylogDate>>>
export type GetStudylogDateInfiniteQueryError = ErrorType<void>


export function useGetStudylogDateInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylogDate>>>, TError = ErrorType<void>>(
 params: undefined |  GetStudylogDateParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogDate>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylogDate>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylogDateInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylogDate>>>, TError = ErrorType<void>>(
 params?: GetStudylogDateParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogDate>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylogDate>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylogDateInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylogDate>>>, TError = ErrorType<void>>(
 params?: GetStudylogDateParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogDate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary Get StudyLog by Date
 */

export function useGetStudylogDateInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylogDate>>>, TError = ErrorType<void>>(
 params?: GetStudylogDateParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogDate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetStudylogDateInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions) as  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getGetStudylogDateQueryOptions = <TData = Awaited<ReturnType<typeof getStudylogDate>>, TError = ErrorType<void>>(params?: GetStudylogDateParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogDate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStudylogDateQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStudylogDate>>> = ({ signal }) => getStudylogDate(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStudylogDate>>, TError, TData> & { queryKey: QueryKey }
}

export type GetStudylogDateQueryResult = NonNullable<Awaited<ReturnType<typeof getStudylogDate>>>
export type GetStudylogDateQueryError = ErrorType<void>


export function useGetStudylogDate<TData = Awaited<ReturnType<typeof getStudylogDate>>, TError = ErrorType<void>>(
 params: undefined |  GetStudylogDateParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogDate>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylogDate>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylogDate<TData = Awaited<ReturnType<typeof getStudylogDate>>, TError = ErrorType<void>>(
 params?: GetStudylogDateParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogDate>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylogDate>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylogDate<TData = Awaited<ReturnType<typeof getStudylogDate>>, TError = ErrorType<void>>(
 params?: GetStudylogDateParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogDate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary Get StudyLog by Date
 */

export function useGetStudylogDate<TData = Awaited<ReturnType<typeof getStudylogDate>>, TError = ErrorType<void>>(
 params?: GetStudylogDateParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogDate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetStudylogDateQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get StudyLog Detail by ID
 */
export const getStudylogDetailId = (
    id: string,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<StudylogctrlMyStudyLogDTO>(
      {url: `/studylog/detail/${id}`, method: 'GET', signal
    },
      options);
    }
  

export const getGetStudylogDetailIdQueryKey = (id: string,) => {
    return [`/studylog/detail/${id}`] as const;
    }

    
export const getGetStudylogDetailIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getStudylogDetailId>>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogDetailId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStudylogDetailIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStudylogDetailId>>> = ({ signal }) => getStudylogDetailId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogDetailId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetStudylogDetailIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getStudylogDetailId>>>
export type GetStudylogDetailIdInfiniteQueryError = ErrorType<void>


export function useGetStudylogDetailIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylogDetailId>>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogDetailId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylogDetailId>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylogDetailIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylogDetailId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogDetailId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylogDetailId>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylogDetailIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylogDetailId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogDetailId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary Get StudyLog Detail by ID
 */

export function useGetStudylogDetailIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylogDetailId>>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogDetailId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetStudylogDetailIdInfiniteQueryOptions(id,options)

  const query = useInfiniteQuery(queryOptions) as  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getGetStudylogDetailIdQueryOptions = <TData = Awaited<ReturnType<typeof getStudylogDetailId>>, TError = ErrorType<void>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogDetailId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStudylogDetailIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStudylogDetailId>>> = ({ signal }) => getStudylogDetailId(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStudylogDetailId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetStudylogDetailIdQueryResult = NonNullable<Awaited<ReturnType<typeof getStudylogDetailId>>>
export type GetStudylogDetailIdQueryError = ErrorType<void>


export function useGetStudylogDetailId<TData = Awaited<ReturnType<typeof getStudylogDetailId>>, TError = ErrorType<void>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogDetailId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylogDetailId>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylogDetailId<TData = Awaited<ReturnType<typeof getStudylogDetailId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogDetailId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylogDetailId>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylogDetailId<TData = Awaited<ReturnType<typeof getStudylogDetailId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogDetailId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary Get StudyLog Detail by ID
 */

export function useGetStudylogDetailId<TData = Awaited<ReturnType<typeof getStudylogDetailId>>, TError = ErrorType<void>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogDetailId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetStudylogDetailIdQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get Statistics with Term
 */
export const getStudylogGroupStatisticsTermGroupIdMemberId = (
    groupId: string,
    memberId: string,
    params: GetStudylogGroupStatisticsTermGroupIdMemberIdParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<StudylogctrlGroupMemberdailyStudyLog[]>(
      {url: `/studylog/group/statistics/term/${groupId}/${memberId}`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getGetStudylogGroupStatisticsTermGroupIdMemberIdQueryKey = (groupId: string,
    memberId: string,
    params: GetStudylogGroupStatisticsTermGroupIdMemberIdParams,) => {
    return [`/studylog/group/statistics/term/${groupId}/${memberId}`, ...(params ? [params]: [])] as const;
    }

    
export const getGetStudylogGroupStatisticsTermGroupIdMemberIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getStudylogGroupStatisticsTermGroupIdMemberId>>>, TError = ErrorType<void>>(groupId: string,
    memberId: string,
    params: GetStudylogGroupStatisticsTermGroupIdMemberIdParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogGroupStatisticsTermGroupIdMemberId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStudylogGroupStatisticsTermGroupIdMemberIdQueryKey(groupId,memberId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStudylogGroupStatisticsTermGroupIdMemberId>>> = ({ signal }) => getStudylogGroupStatisticsTermGroupIdMemberId(groupId,memberId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(groupId && memberId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogGroupStatisticsTermGroupIdMemberId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetStudylogGroupStatisticsTermGroupIdMemberIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getStudylogGroupStatisticsTermGroupIdMemberId>>>
export type GetStudylogGroupStatisticsTermGroupIdMemberIdInfiniteQueryError = ErrorType<void>


export function useGetStudylogGroupStatisticsTermGroupIdMemberIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylogGroupStatisticsTermGroupIdMemberId>>>, TError = ErrorType<void>>(
 groupId: string,
    memberId: string,
    params: GetStudylogGroupStatisticsTermGroupIdMemberIdParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogGroupStatisticsTermGroupIdMemberId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylogGroupStatisticsTermGroupIdMemberId>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylogGroupStatisticsTermGroupIdMemberIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylogGroupStatisticsTermGroupIdMemberId>>>, TError = ErrorType<void>>(
 groupId: string,
    memberId: string,
    params: GetStudylogGroupStatisticsTermGroupIdMemberIdParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogGroupStatisticsTermGroupIdMemberId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylogGroupStatisticsTermGroupIdMemberId>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylogGroupStatisticsTermGroupIdMemberIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylogGroupStatisticsTermGroupIdMemberId>>>, TError = ErrorType<void>>(
 groupId: string,
    memberId: string,
    params: GetStudylogGroupStatisticsTermGroupIdMemberIdParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogGroupStatisticsTermGroupIdMemberId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary Get Statistics with Term
 */

export function useGetStudylogGroupStatisticsTermGroupIdMemberIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylogGroupStatisticsTermGroupIdMemberId>>>, TError = ErrorType<void>>(
 groupId: string,
    memberId: string,
    params: GetStudylogGroupStatisticsTermGroupIdMemberIdParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogGroupStatisticsTermGroupIdMemberId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetStudylogGroupStatisticsTermGroupIdMemberIdInfiniteQueryOptions(groupId,memberId,params,options)

  const query = useInfiniteQuery(queryOptions) as  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getGetStudylogGroupStatisticsTermGroupIdMemberIdQueryOptions = <TData = Awaited<ReturnType<typeof getStudylogGroupStatisticsTermGroupIdMemberId>>, TError = ErrorType<void>>(groupId: string,
    memberId: string,
    params: GetStudylogGroupStatisticsTermGroupIdMemberIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogGroupStatisticsTermGroupIdMemberId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStudylogGroupStatisticsTermGroupIdMemberIdQueryKey(groupId,memberId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStudylogGroupStatisticsTermGroupIdMemberId>>> = ({ signal }) => getStudylogGroupStatisticsTermGroupIdMemberId(groupId,memberId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(groupId && memberId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStudylogGroupStatisticsTermGroupIdMemberId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetStudylogGroupStatisticsTermGroupIdMemberIdQueryResult = NonNullable<Awaited<ReturnType<typeof getStudylogGroupStatisticsTermGroupIdMemberId>>>
export type GetStudylogGroupStatisticsTermGroupIdMemberIdQueryError = ErrorType<void>


export function useGetStudylogGroupStatisticsTermGroupIdMemberId<TData = Awaited<ReturnType<typeof getStudylogGroupStatisticsTermGroupIdMemberId>>, TError = ErrorType<void>>(
 groupId: string,
    memberId: string,
    params: GetStudylogGroupStatisticsTermGroupIdMemberIdParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogGroupStatisticsTermGroupIdMemberId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylogGroupStatisticsTermGroupIdMemberId>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylogGroupStatisticsTermGroupIdMemberId<TData = Awaited<ReturnType<typeof getStudylogGroupStatisticsTermGroupIdMemberId>>, TError = ErrorType<void>>(
 groupId: string,
    memberId: string,
    params: GetStudylogGroupStatisticsTermGroupIdMemberIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogGroupStatisticsTermGroupIdMemberId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylogGroupStatisticsTermGroupIdMemberId>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylogGroupStatisticsTermGroupIdMemberId<TData = Awaited<ReturnType<typeof getStudylogGroupStatisticsTermGroupIdMemberId>>, TError = ErrorType<void>>(
 groupId: string,
    memberId: string,
    params: GetStudylogGroupStatisticsTermGroupIdMemberIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogGroupStatisticsTermGroupIdMemberId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary Get Statistics with Term
 */

export function useGetStudylogGroupStatisticsTermGroupIdMemberId<TData = Awaited<ReturnType<typeof getStudylogGroupStatisticsTermGroupIdMemberId>>, TError = ErrorType<void>>(
 groupId: string,
    memberId: string,
    params: GetStudylogGroupStatisticsTermGroupIdMemberIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogGroupStatisticsTermGroupIdMemberId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetStudylogGroupStatisticsTermGroupIdMemberIdQueryOptions(groupId,memberId,params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get StudyLogs with Term with Group
 */
export const getStudylogGroupTermGroupIdMemberId = (
    groupId: string,
    memberId: string,
    params: GetStudylogGroupTermGroupIdMemberIdParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<StudylogctrlGroupStudyLogDTO[]>(
      {url: `/studylog/group/term/${groupId}/${memberId}`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getGetStudylogGroupTermGroupIdMemberIdQueryKey = (groupId: string,
    memberId: string,
    params: GetStudylogGroupTermGroupIdMemberIdParams,) => {
    return [`/studylog/group/term/${groupId}/${memberId}`, ...(params ? [params]: [])] as const;
    }

    
export const getGetStudylogGroupTermGroupIdMemberIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getStudylogGroupTermGroupIdMemberId>>>, TError = ErrorType<void>>(groupId: string,
    memberId: string,
    params: GetStudylogGroupTermGroupIdMemberIdParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogGroupTermGroupIdMemberId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStudylogGroupTermGroupIdMemberIdQueryKey(groupId,memberId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStudylogGroupTermGroupIdMemberId>>> = ({ signal }) => getStudylogGroupTermGroupIdMemberId(groupId,memberId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(groupId && memberId), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogGroupTermGroupIdMemberId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetStudylogGroupTermGroupIdMemberIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getStudylogGroupTermGroupIdMemberId>>>
export type GetStudylogGroupTermGroupIdMemberIdInfiniteQueryError = ErrorType<void>


export function useGetStudylogGroupTermGroupIdMemberIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylogGroupTermGroupIdMemberId>>>, TError = ErrorType<void>>(
 groupId: string,
    memberId: string,
    params: GetStudylogGroupTermGroupIdMemberIdParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogGroupTermGroupIdMemberId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylogGroupTermGroupIdMemberId>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylogGroupTermGroupIdMemberIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylogGroupTermGroupIdMemberId>>>, TError = ErrorType<void>>(
 groupId: string,
    memberId: string,
    params: GetStudylogGroupTermGroupIdMemberIdParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogGroupTermGroupIdMemberId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylogGroupTermGroupIdMemberId>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylogGroupTermGroupIdMemberIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylogGroupTermGroupIdMemberId>>>, TError = ErrorType<void>>(
 groupId: string,
    memberId: string,
    params: GetStudylogGroupTermGroupIdMemberIdParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogGroupTermGroupIdMemberId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary Get StudyLogs with Term with Group
 */

export function useGetStudylogGroupTermGroupIdMemberIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylogGroupTermGroupIdMemberId>>>, TError = ErrorType<void>>(
 groupId: string,
    memberId: string,
    params: GetStudylogGroupTermGroupIdMemberIdParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogGroupTermGroupIdMemberId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetStudylogGroupTermGroupIdMemberIdInfiniteQueryOptions(groupId,memberId,params,options)

  const query = useInfiniteQuery(queryOptions) as  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getGetStudylogGroupTermGroupIdMemberIdQueryOptions = <TData = Awaited<ReturnType<typeof getStudylogGroupTermGroupIdMemberId>>, TError = ErrorType<void>>(groupId: string,
    memberId: string,
    params: GetStudylogGroupTermGroupIdMemberIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogGroupTermGroupIdMemberId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStudylogGroupTermGroupIdMemberIdQueryKey(groupId,memberId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStudylogGroupTermGroupIdMemberId>>> = ({ signal }) => getStudylogGroupTermGroupIdMemberId(groupId,memberId,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(groupId && memberId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStudylogGroupTermGroupIdMemberId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetStudylogGroupTermGroupIdMemberIdQueryResult = NonNullable<Awaited<ReturnType<typeof getStudylogGroupTermGroupIdMemberId>>>
export type GetStudylogGroupTermGroupIdMemberIdQueryError = ErrorType<void>


export function useGetStudylogGroupTermGroupIdMemberId<TData = Awaited<ReturnType<typeof getStudylogGroupTermGroupIdMemberId>>, TError = ErrorType<void>>(
 groupId: string,
    memberId: string,
    params: GetStudylogGroupTermGroupIdMemberIdParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogGroupTermGroupIdMemberId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylogGroupTermGroupIdMemberId>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylogGroupTermGroupIdMemberId<TData = Awaited<ReturnType<typeof getStudylogGroupTermGroupIdMemberId>>, TError = ErrorType<void>>(
 groupId: string,
    memberId: string,
    params: GetStudylogGroupTermGroupIdMemberIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogGroupTermGroupIdMemberId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylogGroupTermGroupIdMemberId>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylogGroupTermGroupIdMemberId<TData = Awaited<ReturnType<typeof getStudylogGroupTermGroupIdMemberId>>, TError = ErrorType<void>>(
 groupId: string,
    memberId: string,
    params: GetStudylogGroupTermGroupIdMemberIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogGroupTermGroupIdMemberId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary Get StudyLogs with Term with Group
 */

export function useGetStudylogGroupTermGroupIdMemberId<TData = Awaited<ReturnType<typeof getStudylogGroupTermGroupIdMemberId>>, TError = ErrorType<void>>(
 groupId: string,
    memberId: string,
    params: GetStudylogGroupTermGroupIdMemberIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogGroupTermGroupIdMemberId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetStudylogGroupTermGroupIdMemberIdQueryOptions(groupId,memberId,params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get statistics of study logs with date
 */
export const getStudylogStatisticsDate = (
    params?: GetStudylogStatisticsDateParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<StudylogctrlDailySubjectLog[]>(
      {url: `/studylog/statistics/date`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getGetStudylogStatisticsDateQueryKey = (params?: GetStudylogStatisticsDateParams,) => {
    return [`/studylog/statistics/date`, ...(params ? [params]: [])] as const;
    }

    
export const getGetStudylogStatisticsDateInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getStudylogStatisticsDate>>>, TError = ErrorType<void>>(params?: GetStudylogStatisticsDateParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogStatisticsDate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStudylogStatisticsDateQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStudylogStatisticsDate>>> = ({ signal }) => getStudylogStatisticsDate(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogStatisticsDate>>, TError, TData> & { queryKey: QueryKey }
}

export type GetStudylogStatisticsDateInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getStudylogStatisticsDate>>>
export type GetStudylogStatisticsDateInfiniteQueryError = ErrorType<void>


export function useGetStudylogStatisticsDateInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylogStatisticsDate>>>, TError = ErrorType<void>>(
 params: undefined |  GetStudylogStatisticsDateParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogStatisticsDate>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylogStatisticsDate>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylogStatisticsDateInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylogStatisticsDate>>>, TError = ErrorType<void>>(
 params?: GetStudylogStatisticsDateParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogStatisticsDate>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylogStatisticsDate>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylogStatisticsDateInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylogStatisticsDate>>>, TError = ErrorType<void>>(
 params?: GetStudylogStatisticsDateParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogStatisticsDate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary Get statistics of study logs with date
 */

export function useGetStudylogStatisticsDateInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylogStatisticsDate>>>, TError = ErrorType<void>>(
 params?: GetStudylogStatisticsDateParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogStatisticsDate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetStudylogStatisticsDateInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions) as  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getGetStudylogStatisticsDateQueryOptions = <TData = Awaited<ReturnType<typeof getStudylogStatisticsDate>>, TError = ErrorType<void>>(params?: GetStudylogStatisticsDateParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogStatisticsDate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStudylogStatisticsDateQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStudylogStatisticsDate>>> = ({ signal }) => getStudylogStatisticsDate(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStudylogStatisticsDate>>, TError, TData> & { queryKey: QueryKey }
}

export type GetStudylogStatisticsDateQueryResult = NonNullable<Awaited<ReturnType<typeof getStudylogStatisticsDate>>>
export type GetStudylogStatisticsDateQueryError = ErrorType<void>


export function useGetStudylogStatisticsDate<TData = Awaited<ReturnType<typeof getStudylogStatisticsDate>>, TError = ErrorType<void>>(
 params: undefined |  GetStudylogStatisticsDateParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogStatisticsDate>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylogStatisticsDate>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylogStatisticsDate<TData = Awaited<ReturnType<typeof getStudylogStatisticsDate>>, TError = ErrorType<void>>(
 params?: GetStudylogStatisticsDateParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogStatisticsDate>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylogStatisticsDate>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylogStatisticsDate<TData = Awaited<ReturnType<typeof getStudylogStatisticsDate>>, TError = ErrorType<void>>(
 params?: GetStudylogStatisticsDateParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogStatisticsDate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary Get statistics of study logs with date
 */

export function useGetStudylogStatisticsDate<TData = Awaited<ReturnType<typeof getStudylogStatisticsDate>>, TError = ErrorType<void>>(
 params?: GetStudylogStatisticsDateParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogStatisticsDate>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetStudylogStatisticsDateQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get Statistics with Term
 */
export const getStudylogStatisticsTerm = (
    params: GetStudylogStatisticsTermParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<StudylogctrlDailyStudyLog[]>(
      {url: `/studylog/statistics/term`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getGetStudylogStatisticsTermQueryKey = (params: GetStudylogStatisticsTermParams,) => {
    return [`/studylog/statistics/term`, ...(params ? [params]: [])] as const;
    }

    
export const getGetStudylogStatisticsTermInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getStudylogStatisticsTerm>>>, TError = ErrorType<void>>(params: GetStudylogStatisticsTermParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogStatisticsTerm>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStudylogStatisticsTermQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStudylogStatisticsTerm>>> = ({ signal }) => getStudylogStatisticsTerm(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogStatisticsTerm>>, TError, TData> & { queryKey: QueryKey }
}

export type GetStudylogStatisticsTermInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getStudylogStatisticsTerm>>>
export type GetStudylogStatisticsTermInfiniteQueryError = ErrorType<void>


export function useGetStudylogStatisticsTermInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylogStatisticsTerm>>>, TError = ErrorType<void>>(
 params: GetStudylogStatisticsTermParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogStatisticsTerm>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylogStatisticsTerm>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylogStatisticsTermInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylogStatisticsTerm>>>, TError = ErrorType<void>>(
 params: GetStudylogStatisticsTermParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogStatisticsTerm>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylogStatisticsTerm>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylogStatisticsTermInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylogStatisticsTerm>>>, TError = ErrorType<void>>(
 params: GetStudylogStatisticsTermParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogStatisticsTerm>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary Get Statistics with Term
 */

export function useGetStudylogStatisticsTermInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylogStatisticsTerm>>>, TError = ErrorType<void>>(
 params: GetStudylogStatisticsTermParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogStatisticsTerm>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetStudylogStatisticsTermInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions) as  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getGetStudylogStatisticsTermQueryOptions = <TData = Awaited<ReturnType<typeof getStudylogStatisticsTerm>>, TError = ErrorType<void>>(params: GetStudylogStatisticsTermParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogStatisticsTerm>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStudylogStatisticsTermQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStudylogStatisticsTerm>>> = ({ signal }) => getStudylogStatisticsTerm(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStudylogStatisticsTerm>>, TError, TData> & { queryKey: QueryKey }
}

export type GetStudylogStatisticsTermQueryResult = NonNullable<Awaited<ReturnType<typeof getStudylogStatisticsTerm>>>
export type GetStudylogStatisticsTermQueryError = ErrorType<void>


export function useGetStudylogStatisticsTerm<TData = Awaited<ReturnType<typeof getStudylogStatisticsTerm>>, TError = ErrorType<void>>(
 params: GetStudylogStatisticsTermParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogStatisticsTerm>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylogStatisticsTerm>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylogStatisticsTerm<TData = Awaited<ReturnType<typeof getStudylogStatisticsTerm>>, TError = ErrorType<void>>(
 params: GetStudylogStatisticsTermParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogStatisticsTerm>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylogStatisticsTerm>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylogStatisticsTerm<TData = Awaited<ReturnType<typeof getStudylogStatisticsTerm>>, TError = ErrorType<void>>(
 params: GetStudylogStatisticsTermParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogStatisticsTerm>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary Get Statistics with Term
 */

export function useGetStudylogStatisticsTerm<TData = Awaited<ReturnType<typeof getStudylogStatisticsTerm>>, TError = ErrorType<void>>(
 params: GetStudylogStatisticsTermParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogStatisticsTerm>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetStudylogStatisticsTermQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get Study Log with Subject
 */
export const getStudylogSubjectId = (
    id: string,
    params: GetStudylogSubjectIdParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<StudylogctrlMyStudyLogDTO[]>(
      {url: `/studylog/subject/${id}`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getGetStudylogSubjectIdQueryKey = (id: string,
    params: GetStudylogSubjectIdParams,) => {
    return [`/studylog/subject/${id}`, ...(params ? [params]: [])] as const;
    }

    
export const getGetStudylogSubjectIdInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getStudylogSubjectId>>>, TError = ErrorType<unknown>>(id: string,
    params: GetStudylogSubjectIdParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogSubjectId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStudylogSubjectIdQueryKey(id,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStudylogSubjectId>>> = ({ signal }) => getStudylogSubjectId(id,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogSubjectId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetStudylogSubjectIdInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getStudylogSubjectId>>>
export type GetStudylogSubjectIdInfiniteQueryError = ErrorType<unknown>


export function useGetStudylogSubjectIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylogSubjectId>>>, TError = ErrorType<unknown>>(
 id: string,
    params: GetStudylogSubjectIdParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogSubjectId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylogSubjectId>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylogSubjectIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylogSubjectId>>>, TError = ErrorType<unknown>>(
 id: string,
    params: GetStudylogSubjectIdParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogSubjectId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylogSubjectId>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylogSubjectIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylogSubjectId>>>, TError = ErrorType<unknown>>(
 id: string,
    params: GetStudylogSubjectIdParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogSubjectId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary Get Study Log with Subject
 */

export function useGetStudylogSubjectIdInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylogSubjectId>>>, TError = ErrorType<unknown>>(
 id: string,
    params: GetStudylogSubjectIdParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogSubjectId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetStudylogSubjectIdInfiniteQueryOptions(id,params,options)

  const query = useInfiniteQuery(queryOptions) as  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getGetStudylogSubjectIdQueryOptions = <TData = Awaited<ReturnType<typeof getStudylogSubjectId>>, TError = ErrorType<unknown>>(id: string,
    params: GetStudylogSubjectIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogSubjectId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStudylogSubjectIdQueryKey(id,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStudylogSubjectId>>> = ({ signal }) => getStudylogSubjectId(id,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStudylogSubjectId>>, TError, TData> & { queryKey: QueryKey }
}

export type GetStudylogSubjectIdQueryResult = NonNullable<Awaited<ReturnType<typeof getStudylogSubjectId>>>
export type GetStudylogSubjectIdQueryError = ErrorType<unknown>


export function useGetStudylogSubjectId<TData = Awaited<ReturnType<typeof getStudylogSubjectId>>, TError = ErrorType<unknown>>(
 id: string,
    params: GetStudylogSubjectIdParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogSubjectId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylogSubjectId>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylogSubjectId<TData = Awaited<ReturnType<typeof getStudylogSubjectId>>, TError = ErrorType<unknown>>(
 id: string,
    params: GetStudylogSubjectIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogSubjectId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylogSubjectId>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylogSubjectId<TData = Awaited<ReturnType<typeof getStudylogSubjectId>>, TError = ErrorType<unknown>>(
 id: string,
    params: GetStudylogSubjectIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogSubjectId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary Get Study Log with Subject
 */

export function useGetStudylogSubjectId<TData = Awaited<ReturnType<typeof getStudylogSubjectId>>, TError = ErrorType<unknown>>(
 id: string,
    params: GetStudylogSubjectIdParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogSubjectId>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetStudylogSubjectIdQueryOptions(id,params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get StudyLogs with Term
 */
export const getStudylogTerm = (
    params: GetStudylogTermParams,
 options?: SecondParameter<typeof customInstance>,signal?: AbortSignal
) => {
      
      
      return customInstance<StudylogctrlMyStudyLogDTO[]>(
      {url: `/studylog/term`, method: 'GET',
        params, signal
    },
      options);
    }
  

export const getGetStudylogTermQueryKey = (params: GetStudylogTermParams,) => {
    return [`/studylog/term`, ...(params ? [params]: [])] as const;
    }

    
export const getGetStudylogTermInfiniteQueryOptions = <TData = InfiniteData<Awaited<ReturnType<typeof getStudylogTerm>>>, TError = ErrorType<void>>(params: GetStudylogTermParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogTerm>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStudylogTermQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStudylogTerm>>> = ({ signal }) => getStudylogTerm(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogTerm>>, TError, TData> & { queryKey: QueryKey }
}

export type GetStudylogTermInfiniteQueryResult = NonNullable<Awaited<ReturnType<typeof getStudylogTerm>>>
export type GetStudylogTermInfiniteQueryError = ErrorType<void>


export function useGetStudylogTermInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylogTerm>>>, TError = ErrorType<void>>(
 params: GetStudylogTermParams, options: { query:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogTerm>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylogTerm>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  DefinedUseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylogTermInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylogTerm>>>, TError = ErrorType<void>>(
 params: GetStudylogTermParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogTerm>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylogTerm>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylogTermInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylogTerm>>>, TError = ErrorType<void>>(
 params: GetStudylogTermParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogTerm>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary Get StudyLogs with Term
 */

export function useGetStudylogTermInfinite<TData = InfiniteData<Awaited<ReturnType<typeof getStudylogTerm>>>, TError = ErrorType<void>>(
 params: GetStudylogTermParams, options?: { query?:Partial<UseInfiniteQueryOptions<Awaited<ReturnType<typeof getStudylogTerm>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetStudylogTermInfiniteQueryOptions(params,options)

  const query = useInfiniteQuery(queryOptions) as  UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getGetStudylogTermQueryOptions = <TData = Awaited<ReturnType<typeof getStudylogTerm>>, TError = ErrorType<void>>(params: GetStudylogTermParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogTerm>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStudylogTermQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStudylogTerm>>> = ({ signal }) => getStudylogTerm(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStudylogTerm>>, TError, TData> & { queryKey: QueryKey }
}

export type GetStudylogTermQueryResult = NonNullable<Awaited<ReturnType<typeof getStudylogTerm>>>
export type GetStudylogTermQueryError = ErrorType<void>


export function useGetStudylogTerm<TData = Awaited<ReturnType<typeof getStudylogTerm>>, TError = ErrorType<void>>(
 params: GetStudylogTermParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogTerm>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylogTerm>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylogTerm<TData = Awaited<ReturnType<typeof getStudylogTerm>>, TError = ErrorType<void>>(
 params: GetStudylogTermParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogTerm>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStudylogTerm>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
export function useGetStudylogTerm<TData = Awaited<ReturnType<typeof getStudylogTerm>>, TError = ErrorType<void>>(
 params: GetStudylogTermParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogTerm>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey }
/**
 * @summary Get StudyLogs with Term
 */

export function useGetStudylogTerm<TData = Awaited<ReturnType<typeof getStudylogTerm>>, TError = ErrorType<void>>(
 params: GetStudylogTermParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStudylogTerm>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetStudylogTermQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Modify Study Log
 */
export const putStudylogId = (
    id: string,
    studylogctrlCreateStudyLogReqBody: BodyType<StudylogctrlCreateStudyLogReqBody>,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<StudylogctrlCreateStudyLogReq>(
      {url: `/studylog/${id}`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: studylogctrlCreateStudyLogReqBody
    },
      options);
    }
  


export const getPutStudylogIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putStudylogId>>, TError,{id: string;data: BodyType<StudylogctrlCreateStudyLogReqBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof putStudylogId>>, TError,{id: string;data: BodyType<StudylogctrlCreateStudyLogReqBody>}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putStudylogId>>, {id: string;data: BodyType<StudylogctrlCreateStudyLogReqBody>}> = (props) => {
          const {id,data} = props ?? {};

          return  putStudylogId(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PutStudylogIdMutationResult = NonNullable<Awaited<ReturnType<typeof putStudylogId>>>
    export type PutStudylogIdMutationBody = BodyType<StudylogctrlCreateStudyLogReqBody>
    export type PutStudylogIdMutationError = ErrorType<void>

    /**
 * @summary Modify Study Log
 */
export const usePutStudylogId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putStudylogId>>, TError,{id: string;data: BodyType<StudylogctrlCreateStudyLogReqBody>}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof putStudylogId>>,
        TError,
        {id: string;data: BodyType<StudylogctrlCreateStudyLogReqBody>},
        TContext
      > => {

      const mutationOptions = getPutStudylogIdMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary Delete StudyLog
 */
export const deleteStudylogId = (
    id: string,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<void>(
      {url: `/studylog/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getDeleteStudylogIdMutationOptions = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteStudylogId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteStudylogId>>, TError,{id: string}, TContext> => {
const {mutation: mutationOptions, request: requestOptions} = options ?? {};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteStudylogId>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteStudylogId(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteStudylogIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteStudylogId>>>
    
    export type DeleteStudylogIdMutationError = ErrorType<void>

    /**
 * @summary Delete StudyLog
 */
export const useDeleteStudylogId = <TError = ErrorType<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteStudylogId>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        Awaited<ReturnType<typeof deleteStudylogId>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteStudylogIdMutationOptions(options);

      return useMutation(mutationOptions);
    }
    