/**
 * Generated by orval v7.0.1 🍺
 * Do not edit manually.
 * Distimer Swagger API
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker'
import {
  HttpResponse,
  delay,
  http
} from 'msw'
import type {
  StudylogctrlCreateStudyLogReq,
  StudylogctrlDailyStudyLog,
  StudylogctrlDailySubjectLog,
  StudylogctrlGroupMemberdailyStudyLog,
  StudylogctrlGroupStudyLogDTO,
  StudylogctrlMyStudyLogDTO
} from '../../schemas'

export const getGetStudylogResponseMock = (): StudylogctrlMyStudyLogDTO[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({content: faker.word.sample(), end_at: faker.word.sample(), groups_to_share: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), id: faker.word.sample(), start_at: faker.word.sample(), subject_id: faker.word.sample()})))

export const getPostStudylogResponseMock = (overrideResponse: Partial< StudylogctrlMyStudyLogDTO > = {}): StudylogctrlMyStudyLogDTO => ({content: faker.word.sample(), end_at: faker.word.sample(), groups_to_share: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), id: faker.word.sample(), start_at: faker.word.sample(), subject_id: faker.word.sample(), ...overrideResponse})

export const getGetStudylogDateResponseMock = (): StudylogctrlMyStudyLogDTO[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({content: faker.word.sample(), end_at: faker.word.sample(), groups_to_share: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), id: faker.word.sample(), start_at: faker.word.sample(), subject_id: faker.word.sample()})))

export const getGetStudylogDetailIdResponseMock = (overrideResponse: Partial< StudylogctrlMyStudyLogDTO > = {}): StudylogctrlMyStudyLogDTO => ({content: faker.word.sample(), end_at: faker.word.sample(), groups_to_share: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), id: faker.word.sample(), start_at: faker.word.sample(), subject_id: faker.word.sample(), ...overrideResponse})

export const getGetStudylogGroupStatisticsTermGroupIdMemberIdResponseMock = (): StudylogctrlGroupMemberdailyStudyLog[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({date: faker.word.sample(), log: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({category_id: faker.word.sample(), category_name: faker.word.sample(), study_time: faker.number.int({min: undefined, max: undefined}), subject: {color: faker.word.sample(), id: faker.word.sample(), name: faker.word.sample(), order: faker.number.int({min: 0, max: undefined})}}))})))

export const getGetStudylogGroupTermGroupIdMemberIdResponseMock = (): StudylogctrlGroupStudyLogDTO[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({category_id: faker.word.sample(), category_name: faker.word.sample(), content: faker.word.sample(), end_at: faker.word.sample(), id: faker.word.sample(), start_at: faker.word.sample(), subject: {color: faker.word.sample(), id: faker.word.sample(), name: faker.word.sample(), order: faker.number.int({min: 0, max: undefined})}})))

export const getGetStudylogStatisticsDateResponseMock = (): StudylogctrlDailySubjectLog[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({category_id: faker.word.sample(), study_time: faker.number.int({min: undefined, max: undefined}), subject_id: faker.word.sample()})))

export const getGetStudylogStatisticsTermResponseMock = (): StudylogctrlDailyStudyLog[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({date: faker.word.sample(), log: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({category_id: faker.word.sample(), study_time: faker.number.int({min: undefined, max: undefined}), subject_id: faker.word.sample()}))})))

export const getGetStudylogSubjectIdResponseMock = (): StudylogctrlMyStudyLogDTO[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({content: faker.word.sample(), end_at: faker.word.sample(), groups_to_share: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), id: faker.word.sample(), start_at: faker.word.sample(), subject_id: faker.word.sample()})))

export const getGetStudylogTermResponseMock = (): StudylogctrlMyStudyLogDTO[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({content: faker.word.sample(), end_at: faker.word.sample(), groups_to_share: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), id: faker.word.sample(), start_at: faker.word.sample(), subject_id: faker.word.sample()})))

export const getPutStudylogIdResponseMock = (overrideResponse: Partial< StudylogctrlCreateStudyLogReq > = {}): StudylogctrlCreateStudyLogReq => ({content: faker.word.sample(), end_at: faker.word.sample(), groups_to_share: Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => (faker.word.sample())), start_at: faker.word.sample(), subject_id: faker.word.sample(), ...overrideResponse})


export const getGetStudylogMockHandler = (overrideResponse?: StudylogctrlMyStudyLogDTO[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<StudylogctrlMyStudyLogDTO[]> | StudylogctrlMyStudyLogDTO[])) => {
  return http.get('*/studylog', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetStudylogResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getPostStudylogMockHandler = (overrideResponse?: StudylogctrlMyStudyLogDTO | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<StudylogctrlMyStudyLogDTO> | StudylogctrlMyStudyLogDTO)) => {
  return http.post('*/studylog', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getPostStudylogResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getGetStudylogDateMockHandler = (overrideResponse?: StudylogctrlMyStudyLogDTO[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<StudylogctrlMyStudyLogDTO[]> | StudylogctrlMyStudyLogDTO[])) => {
  return http.get('*/studylog/date', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetStudylogDateResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getGetStudylogDetailIdMockHandler = (overrideResponse?: StudylogctrlMyStudyLogDTO | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<StudylogctrlMyStudyLogDTO> | StudylogctrlMyStudyLogDTO)) => {
  return http.get('*/studylog/detail/:id', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetStudylogDetailIdResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getGetStudylogGroupStatisticsTermGroupIdMemberIdMockHandler = (overrideResponse?: StudylogctrlGroupMemberdailyStudyLog[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<StudylogctrlGroupMemberdailyStudyLog[]> | StudylogctrlGroupMemberdailyStudyLog[])) => {
  return http.get('*/studylog/group/statistics/term/:groupId/:memberId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetStudylogGroupStatisticsTermGroupIdMemberIdResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getGetStudylogGroupTermGroupIdMemberIdMockHandler = (overrideResponse?: StudylogctrlGroupStudyLogDTO[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<StudylogctrlGroupStudyLogDTO[]> | StudylogctrlGroupStudyLogDTO[])) => {
  return http.get('*/studylog/group/term/:groupId/:memberId', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetStudylogGroupTermGroupIdMemberIdResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getGetStudylogStatisticsDateMockHandler = (overrideResponse?: StudylogctrlDailySubjectLog[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<StudylogctrlDailySubjectLog[]> | StudylogctrlDailySubjectLog[])) => {
  return http.get('*/studylog/statistics/date', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetStudylogStatisticsDateResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getGetStudylogStatisticsTermMockHandler = (overrideResponse?: StudylogctrlDailyStudyLog[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<StudylogctrlDailyStudyLog[]> | StudylogctrlDailyStudyLog[])) => {
  return http.get('*/studylog/statistics/term', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetStudylogStatisticsTermResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getGetStudylogSubjectIdMockHandler = (overrideResponse?: StudylogctrlMyStudyLogDTO[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<StudylogctrlMyStudyLogDTO[]> | StudylogctrlMyStudyLogDTO[])) => {
  return http.get('*/studylog/subject/:id', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetStudylogSubjectIdResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getGetStudylogTermMockHandler = (overrideResponse?: StudylogctrlMyStudyLogDTO[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<StudylogctrlMyStudyLogDTO[]> | StudylogctrlMyStudyLogDTO[])) => {
  return http.get('*/studylog/term', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getGetStudylogTermResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getPutStudylogIdMockHandler = (overrideResponse?: StudylogctrlCreateStudyLogReq | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<StudylogctrlCreateStudyLogReq> | StudylogctrlCreateStudyLogReq)) => {
  return http.put('*/studylog/:id', async (info) => {await delay(1000);
  
    return new HttpResponse(JSON.stringify(overrideResponse !== undefined 
            ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse) 
            : getPutStudylogIdResponseMock()),
      { status: 200,
        headers: { 'Content-Type': 'application/json' }
      })
  })
}

export const getDeleteStudylogIdMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void)) => {
  return http.delete('*/studylog/:id', async (info) => {await delay(1000);
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }
    return new HttpResponse(null,
      { status: 204,
        
      })
  })
}
export const getStudyLogMock = () => [
  getGetStudylogMockHandler(),
  getPostStudylogMockHandler(),
  getGetStudylogDateMockHandler(),
  getGetStudylogDetailIdMockHandler(),
  getGetStudylogGroupStatisticsTermGroupIdMemberIdMockHandler(),
  getGetStudylogGroupTermGroupIdMemberIdMockHandler(),
  getGetStudylogStatisticsDateMockHandler(),
  getGetStudylogStatisticsTermMockHandler(),
  getGetStudylogSubjectIdMockHandler(),
  getGetStudylogTermMockHandler(),
  getPutStudylogIdMockHandler(),
  getDeleteStudylogIdMockHandler()
]
